### PR TITLE
Retry command as W3C when MicrosoftWebDriver returns Unknown Error

### LINKED ISSUE #3143: Execute command doesn't use W3C with Edge Webdriver
**Environment (please complete the following information):**
 - **WebdriverIO version:** [4.14.0]
 - **Mode:** [TestRunner mode]
 - **If WDIO Testrunner, running sync/async:** [Sync]
 - **Node.js version:** [8.14.0]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [Edge 44.17763.1.0]
 - **Platform name and version:** [Windows 10 Build 1809]
 - **Additional wdio packages used (if applicable):** [n/a]
- MicrosoftWebDriver Version 10.0.17763.1
- Microsoft Edge 44.17763.1.0
- Microsoft EdgeHTML 18.17763
- Windows 10 build 1809

**Config of WebdriverIO**
```
reporters: ['spec'],
    host: `<redacted>`,
    port: '<redacted>',
    protocol: '<redacted>',
    maxInstances: 1,

    capabilities: [
        {
            browserName: 'MicrosoftEdge',
            osPlatform: 'Windows',
            osVersion: '10',
        },
    ],
```

**Describe the bug**
In Windows 10 build 1809, MicrosoftWebDriver (Edge) now defaults to W3C Mode. It will not accept Json Wire Protocol commands.

Unfortunately, instead of returning Unknown Command when it receives a JWP command in W3C Mode, MicrosoftWebDriver returns Unknown Error. A bug report has been filed here:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19917561/

Due to this, WDIO will not retry the JWP request as a W3C Request because it didn't return Unknown Command
https://github.com/webdriverio-boneyard/v4/blob/767a0cb7796c0635034bfe991fa851ff6f711ff1/lib/protocol/execute.js#L63-L65

While I believe Edge WebDriver should return the proper error, is there any patch that can be done in WDIO in the meantime to retry Unknown Errors with Edge? I'm concerned how long it may take for MicrosoftWebdriver to change this.

**To Reproduce**
1) Update to Windows 10 build 1809
2) Install Edge WebDriver (In an elevated command prompt, `DISM.exe /Online /Add-Capability /CapabilityName:Microsoft.WebDriver~~~~0.0.1.0` ) 
3) Set WDIO capabilities to run against Edge
4) Use the following example script
```
  it('should inject javascript on the page', function () {
    browser.url('http://webdriver.io');
    var result = browser.execute(function(a, b, c, d) {
        return a + b + c + d;
    }, 1, 2, 3, 4)
    console.log(result.value);
  });
```

**Expected behavior**
The test case should pass.
WebdriverIO should retry `/execute` (JWP) with `/execute/sync` (W3C)

**Log**
WebDriverIO & Edge WebDriver logs:
https://gist.github.com/dylanlive/8b1a5db3213433d6e61384e6adf09d5f
(note, the scripts are slightly different in the logs as the edge log I used from an earlier test).

**Additional context**
Related tickets:
- https://github.com/SeleniumHQ/selenium/issues/6464
- https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19917561/

### PR DESCRIPTION
**Pull request by dylanlive**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
This PR will fix https://github.com/webdriverio/webdriverio/issues/3143

MicrosoftWebdriver (which powers edge) will return back "Unknown Command" if it receives a JSON Wire Protocol command while running in W3C Mode (which is now default in recent Windows 10 Releases).

This PR will allow the "Unknown Error" error to be retried.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have proposed the same patch to the new [v5](https://github.com/webdriverio/v5) repository

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)
- I don't believe this is necessary in v5, as I think v5 uses w3c commands by default
- It would be really nice to refine the conditional to (psuedocode) `if (isUnknownError(err) && Browser == "Edge")`, but I'm not sure how to detect the browser in this piece of code

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by christian-bromann** [comment]
Happy to merge once, the CLA is signed.

**Comment by dylanlive** [comment]
Acknowledged - I'm looking into the CLA, and will @ message you when I have an update.

**Comment by dylanlive** [comment]
@christian-bromann Thanks for your patience! CLA is signed.

**Review by christian-bromann — APPROVED** [review]
👍

**Pull request merged**
